name: Complete CI Pipeline

on: workflow_dispatch

jobs:
  complete:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install NPM Dependencies
        run: npm install
        
      - name: Run Unit Tests and Generate Report
        run: npm test --coverage
        
      - name: Bundle Code into ZIP Package
        run: zip -r deployment-package.zip .

      - run: ls -la coverage
        
      #- name: Better Test Reports Action
  # You may pin to the exact commit or the version.
  # uses: mridang/action-test-reporter@720c9c56f73e527681bcb30c33da4ccd62bf70fb
        #uses: mridang/action-test-reporter@v1.3.0
        #with:
          #working-directory: .
          
