name: Dependencies Example
on: workflow_dispatch

jobs:
  Dependencies_example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.3.1
      - name: Setup Node.js environment
        uses: actions/setup-node@v6.0.0
      - name: verification
        run: ls -alhR
